### ISSUE TITLE
Unable to remove iCloud Drive from Sidebar

### ISSUE THREAD

**Issue by shipper-twist** [Ajordat/finder-sidebar-editor#6] opened 2023-11-28 19:33 UTC
(Continuation of [discussion here](https://github.com/robperc/FinderSidebarEditor/issues/10).)

Thanks for that reply. I think the issue is that iCloud Drive isn't under the "Favorites" heading, but is rather its own heading in the Finder Sidebar at this point. Is there any way to edit the code to look under other headings? I'm attaching screenshots of the current Finder Settings window, my own current Sidebar, and the output of mysides in Terminal. As you can see, it only shows the contents of the "Favorites" heading.

I wish I could contribute more to the discussion than a desire for what I'd like to see and showing the current state of things, but this level of scripting is, unfortunately, beyond me. Since you don't have a Mac, I'm happy to answer any questions you might have and would be more than willing to chat via Discord, Zoom, or whatever you like, if you're willing to spare the time. :) 

<img width="374" alt="Screenshot 2023-11-28 at 11 23 19 AM" src="https://github.com/Ajordat/finder-sidebar-editor/assets/136760872/e50c210e-6de3-4624-9dc0-8d8f1901cd30">

<img width="165" alt="Screenshot 2023-11-28 at 11 21 26 AM" src="https://github.com/Ajordat/finder-sidebar-editor/assets/136760872/03e7dc72-8c01-49c3-9c02-f72ea348619f">

<img width="807" alt="Screenshot 2023-11-28 at 11 22 15 AM" src="https://github.com/Ajordat/finder-sidebar-editor/assets/136760872/6a0c56de-7e4c-4484-b3c7-8cdff6e3726b">

**Comment by Ajordat** [comment] 2023-11-28 23:26
So I've been taking a look at this and I believe I know why it happens.

First of all, the reason why "iCloud" does not appear in the list of folders is because of [this line][1]. I suspect both "iCloud" and "AirDrop" (which is also in your Finder but not in the list) were removed because of limitations with `LSSharedFileListItemResolve`.

Or at least I suspect a limitation on it without using the flags [`kLSSharedFileListNoUserInteraction`][2] (0b01) and [`kLSSharedFileListDoNotMountVolumes`][3] (0b10).

So do you think you could try the following and see what happens? These two tests are mutually exclusive, so try one thing and then the other please.

* Remove "iCloud" from the list of exceptions [here][1].
  I'd like to see if that prevention is just an extreme caution or it really fails when attempting to use it. I suspect [it will fail][4], I'm just seeking confirmation (FAFO).

* Add the following lines after the [aforementioned if statement][1]:
    ```
    if name in ["iCloud"]:
        path = LSSharedFileListItemResolve(item, 0b11, None, None)[1]
    ```
  With this I'd like to see if using those flags would help, so instead of passing 0, `0b11` should be equivalent to those two flags.
  I'm sure they could be retrieved from somewhere within the imported libraries, but for the time being let's just test it like this as it's easier.

I'm assuming you feel confident to modify the library code temporarily for a small reproduction, but let me know if it's unfeasible and we will find a way to go through it together.

[1]: https://github.com/Ajordat/finder-sidebar-editor/blob/master/finder_sidebar_editor/FinderSidebarEditor.py#L105-L106
[2]: https://developer.apple.com/documentation/coreservices/1581401-anonymous/klssharedfilelistnouserinteraction?changes=lat_2_3
[3]: https://developer.apple.com/documentation/coreservices/1581401-anonymous/klssharedfilelistdonotmountvolumes?changes=lat_2_3
[4]: https://stackoverflow.com/q/24863571

**Comment by shipper-twist** [comment] 2023-11-29 19:59
Unfortunately, no joy after testing both methods above. :( 

Let's definitely try to do a screen-share session sometime and see if we can make it work. :)

**Comment by Ajordat** [comment] 2023-12-02 20:34
Didn't it fail with any error messages?

I'm okay doing a screensharing session, Discord works for me so lmk what I should join or the username I should add.

**Comment by Ajordat** [comment] 2024-01-17 14:32
Hi @twist-shipper , are you still interested in debugging this?

**Comment by shipper-twist** [comment] 2024-01-17 17:31
Sorry I lost the thread on this. Yes, I very much am. :)

**Comment by Ajordat** [comment] 2024-01-22 09:14
Awesome then, just send me an email so that we can schedule a call.

**Comment by Ajordat** [comment] 2024-04-09 10:09
I'm closing this because I'm not able to reproduce the issue and due to a lack of traction.

**Closed as completed by Ajordat** 2024-04-09 10:09 UTC
Labels: bug
